// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: channel.sql

package main

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const canUserPublishSqlc = `-- name: CanUserPublishSqlc :one
SELECT
  c.can_publish_anyone OR EXISTS (
    SELECT 1 FROM user_channel uc
    WHERE uc.user_id = $1 AND uc.channel_id = c.id AND uc.can_publish = true
  ) AS can_publish
FROM channel c
WHERE c.name = $2
`

type CanUserPublishSqlcParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CanUserPublishSqlc(ctx context.Context, arg CanUserPublishSqlcParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, canUserPublishSqlc, arg.UserID, arg.Name)
	var can_publish sql.NullBool
	err := row.Scan(&can_publish)
	return can_publish, err
}

const canUserSubscribeSqlc = `-- name: CanUserSubscribeSqlc :one
SELECT
  c.can_subscribe_anyone OR EXISTS (
    SELECT 1 FROM user_channel uc
    WHERE uc.user_id = $1 AND uc.channel_id = c.id
  ) AS can_subscribe
FROM channel c
WHERE c.name = $2
`

type CanUserSubscribeSqlcParams struct {
	UserID uuid.UUID
	Name   string
}

func (q *Queries) CanUserSubscribeSqlc(ctx context.Context, arg CanUserSubscribeSqlcParams) (sql.NullBool, error) {
	row := q.db.QueryRowContext(ctx, canUserSubscribeSqlc, arg.UserID, arg.Name)
	var can_subscribe sql.NullBool
	err := row.Scan(&can_subscribe)
	return can_subscribe, err
}

const ensureChannelSqlc = `-- name: EnsureChannelSqlc :exec
INSERT INTO channel (name)
VALUES ($1)
ON CONFLICT (name) DO NOTHING
`

func (q *Queries) EnsureChannelSqlc(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, ensureChannelSqlc, name)
	return err
}

const ensureUserSqlc = `-- name: EnsureUserSqlc :exec
INSERT INTO "user" (id)
VALUES ($1)
ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureUserSqlc(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, ensureUserSqlc, id)
	return err
}
