// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package main

import (
	"github.com/google/uuid"
)

type Channel struct {
	ID                 uuid.UUID
	Name               string
	CanSubscribeAnyone bool
	CanPublishAnyone   bool
}

type User struct {
	ID uuid.UUID
}

type UserChannel struct {
	UserID     uuid.UUID
	ChannelID  uuid.UUID
	CanPublish bool
}
